name: deploy

on:
  push:
    branches:
         - main

jobs:
  build:
     runs-on: ubuntu-latest
     steps:
        - name: check
          uses: actions/checkout@v4
        - name: login to dockerhub
          run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_TOKEN}}
        - name: build docker container
          run: docker build -t lazlovalentin008/wineyardfront .
        - name: push to register
          run: docker push lazlovalentin008/wineyardfront:latest
    
  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
        - name: pull from dockerhub
          run: docker pull lazlovalentin008/wineyardfront:latest
        - name: delete old container
          run: docker rm -f yardfront
        - name: run docker container
          run: docker run -d -p 3000:3000 --name yardfront lazlovalentin008/wineyardfront:latest

