name: deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: docker to EC2
    runs-on: self-hosted

    steps: 
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: login to dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.IMAGE }}:latest
        file: ./Dockerfile
        context: .
        
    - name: executing remote ssh commands using password  
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}  
        username: ${{ secrets.EC2_USERNAME }}  
        key: ${{ secrets.EC2_KEY }} 
        port: ${{ secrets.EC2_PORT }}

        script: | 
            touch deploy.txt
            echo "Great, it works!" >> deploy.txt
            sudo chmod 777 /var/run/docker.sock
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE }}:latest 
            docker stop ${{ secrets.CONTAINER }}
            docker rm ${{ secrets.CONTAINER }} 
            docker rmi ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE }} 
            docker run --name ${{ secrets.CONTAINER }} -d -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE }}
